### ISSUE TITLE
Official Zathura theme for Dracula

### ISSUE THREAD

**Issue by zenorocha** [OfficialOxide/dotfiles#1]
Hello, Dracula creator here 👋 

I saw your [post on Reddit](https://www.reddit.com/r/vimporn/comments/cg4hvc/dracula/ewjj0cn/) and I noticed you created a Zathura theme for Dracula (https://github.com/OfficialOxide/dotfiles/blob/c9413c38c270db3755b8c650454fa98c159a5701/zathura/.config/zathura/zathurarc#L5).

What do you think of transforming that into an official Dracula theme?

Here's more info about that: https://draculatheme.com/contribute

**Comment by oxidist** [comment]
Hello, I think you would find that the original Dracula colorscheme for Zathura is located [here](https://github.com/GuilhermeHaetinger/Dotfiles_i3_aesthetic/blob/master/zathura/zathurarc).
